### ISSUE TITLE
rc-vacation plugin load error.

### ISSUE THREAD

**Issue by jlaib01** [bhuisgen/rc-vacation#43]
Running RC 1.3.8.

After installing rc-vacation, then clicking the vacation button. I get:
[04-Apr-2019 11:58:25 America/Chicago] PHP Fatal error:  Uncaught Error: Call to undefined function raise_error() in /var/www/html/roundcube/plugins/vacation/vacation.php:183
Stack trace:
#0 /var/www/html/roundcube/plugins/vacation/vacation.php(57): vacation->read_data()
#1 /var/www/html/roundcube/program/lib/Roundcube/rcube_plugin_api.php(493): vacation->vacation_init()
#2 /var/www/html/roundcube/index.php(289): rcube_plugin_api->exec_action('plugin.vacation')
#3 {main}
  thrown in /var/www/html/roundcube/plugins/vacation/vacation.php on line 183
Not sure if I'm missing an dependency, and I've looked and can find the release value of the plugin. 
Any help would be very appreciated.
Thanks in advance.

**Comment by jlaib01** [comment]
Update. commented out the raise_error function calls and can now see the vacation input window. Now trying to get it to save and recall a vacation setup.

**Comment by jlaib01** [comment]
Now learned that function raise_error is a deprecated function. Does anyone know of plugins compatible with RC 1.3.8 for vacation and forwarding? when I search the plugins on vacation all that comes up is rc-vacation-master.zip
