### ISSUE TITLE
Roundcube 1.4.2: Call to undefined function rcube_html_editor()

### ISSUE THREAD

**Issue by axos88** [bhuisgen/rc-vacation#46]
```
PHP Fatal error:  Uncaught Error: Call to undefined function rcube_html_editor() in /var/www/roundcube/plugins/vacation/vacation.php:139
Stack trace:
#0 /var/www/roundcube/program/include/rcmail_output_html.php(1354): vacation->vacation_form()
#1 [internal function]: rcmail_output_html->xml_command()
#2 /var/www/roundcube/program/include/rcmail_output_html.php(1204): preg_replace_callback()
#3 /var/www/roundcube/program/include/rcmail_output_html.php(776): rcmail_output_html->parse_xml()
#4 /var/www/roundcube/program/include/rcmail_output_html.php(610): rcmail_output_html->parse()
#5 /var/www/roundcube/plugins/vacation/vacation.php(61): rcmail_output_html->send()
#6 /var/www/roundcube/program/lib/Roundcube/rcube_plugin_api.php(494): vacation->vacation_init()
#7 /var/www/roundcube/index.php(288): rcube_plugin_api->exec_action()
#8 {main}
  thrown in /var/www/roundcube/plugins/vacation/vacation.php on line 139

```

**Comment by doktoil-makresh** [comment]
same issue here, with RC 1.3.10+dfsg.1-1~deb10u1

**Comment by sylvainfaivre** [comment]
this is due to this commit : https://github.com/roundcube/roundcubemail/commit/e1165fed8

the plugin seems to work when you replace line 139 in plugins/vacation/vacation.php :

```
                        #rcube_html_editor('identity');
                        rcmail::get_instance()->html_editor('identity');
```

Not tested on production server, use at your own risk.

**Comment by Kofl** [comment]
the default managesieve plugin in roundcube 1.4 can now also do vacation settings
